### ISSUE TITLE
Hey Yuvraj

### ISSUE THREAD

**Issue by karimdakroury** [yuvraj24/WhatsApp-Clone#8]
Hi, hope you are doing good. can you please help me out with my question on slack, i have stuck on it for weeks now and it is very similar to your clone here. Would appreciate any help possible. Thank you in advance.

https://stackoverflow.com/questions/65786115/react-native-updating-a-specific-item-inside-a-flatlist

**Comment by yuvraj24** [comment]
Closing this as this is not an issue related to the repo.
